/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.intermediatebox.avro.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Sample enum in same schema */
@org.apache.avro.specific.AvroGenerated
public class Avro05 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5067497789277002559L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avro05\",\"namespace\":\"dev.intermediatebox.avro.data\",\"doc\":\"Sample enum in same schema\",\"fields\":[{\"name\":\"maritalStatus\",\"type\":{\"type\":\"enum\",\"name\":\"Avro05Enum\",\"symbols\":[\"SINGLE\",\"MARRIED\",\"DIVORCED\",\"UNKNOWN\"]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avro05> ENCODER =
      new BinaryMessageEncoder<Avro05>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avro05> DECODER =
      new BinaryMessageDecoder<Avro05>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Avro05> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Avro05> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Avro05> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Avro05>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Avro05 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Avro05 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Avro05 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Avro05 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private dev.intermediatebox.avro.data.Avro05Enum maritalStatus;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avro05() {}

  /**
   * All-args constructor.
   * @param maritalStatus The new value for maritalStatus
   */
  public Avro05(dev.intermediatebox.avro.data.Avro05Enum maritalStatus) {
    this.maritalStatus = maritalStatus;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return maritalStatus;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: maritalStatus = (dev.intermediatebox.avro.data.Avro05Enum)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'maritalStatus' field.
   * @return The value of the 'maritalStatus' field.
   */
  public dev.intermediatebox.avro.data.Avro05Enum getMaritalStatus() {
    return maritalStatus;
  }


  /**
   * Sets the value of the 'maritalStatus' field.
   * @param value the value to set.
   */
  public void setMaritalStatus(dev.intermediatebox.avro.data.Avro05Enum value) {
    this.maritalStatus = value;
  }

  /**
   * Creates a new Avro05 RecordBuilder.
   * @return A new Avro05 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro05.Builder newBuilder() {
    return new dev.intermediatebox.avro.data.Avro05.Builder();
  }

  /**
   * Creates a new Avro05 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avro05 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro05.Builder newBuilder(dev.intermediatebox.avro.data.Avro05.Builder other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro05.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro05.Builder(other);
    }
  }

  /**
   * Creates a new Avro05 RecordBuilder by copying an existing Avro05 instance.
   * @param other The existing instance to copy.
   * @return A new Avro05 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro05.Builder newBuilder(dev.intermediatebox.avro.data.Avro05 other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro05.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro05.Builder(other);
    }
  }

  /**
   * RecordBuilder for Avro05 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avro05>
    implements org.apache.avro.data.RecordBuilder<Avro05> {

    private dev.intermediatebox.avro.data.Avro05Enum maritalStatus;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro05.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.maritalStatus)) {
        this.maritalStatus = data().deepCopy(fields()[0].schema(), other.maritalStatus);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Avro05 instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro05 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.maritalStatus)) {
        this.maritalStatus = data().deepCopy(fields()[0].schema(), other.maritalStatus);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'maritalStatus' field.
      * @return The value.
      */
    public dev.intermediatebox.avro.data.Avro05Enum getMaritalStatus() {
      return maritalStatus;
    }


    /**
      * Sets the value of the 'maritalStatus' field.
      * @param value The value of 'maritalStatus'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro05.Builder setMaritalStatus(dev.intermediatebox.avro.data.Avro05Enum value) {
      validate(fields()[0], value);
      this.maritalStatus = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'maritalStatus' field has been set.
      * @return True if the 'maritalStatus' field has been set, false otherwise.
      */
    public boolean hasMaritalStatus() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'maritalStatus' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro05.Builder clearMaritalStatus() {
      maritalStatus = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avro05 build() {
      try {
        Avro05 record = new Avro05();
        record.maritalStatus = fieldSetFlags()[0] ? this.maritalStatus : (dev.intermediatebox.avro.data.Avro05Enum) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avro05>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avro05>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avro05>
    READER$ = (org.apache.avro.io.DatumReader<Avro05>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeEnum(this.maritalStatus.ordinal());

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.maritalStatus = dev.intermediatebox.avro.data.Avro05Enum.values()[in.readEnum()];

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.maritalStatus = dev.intermediatebox.avro.data.Avro05Enum.values()[in.readEnum()];
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










