/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.intermediatebox.avro.data;
@org.apache.avro.specific.AvroGenerated
public enum Avro05Enum implements org.apache.avro.generic.GenericEnumSymbol<Avro05Enum> {
  SINGLE, MARRIED, DIVORCED, UNKNOWN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Avro05Enum\",\"namespace\":\"dev.intermediatebox.avro.data\",\"symbols\":[\"SINGLE\",\"MARRIED\",\"DIVORCED\",\"UNKNOWN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
