/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.intermediatebox.avro.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Sample default value */
@org.apache.avro.specific.AvroGenerated
public class Avro01 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5207479249628173361L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avro01\",\"namespace\":\"dev.intermediatebox.avro.data\",\"doc\":\"Sample default value\",\"fields\":[{\"name\":\"fullName\",\"type\":\"string\"},{\"name\":\"maritalStatus\",\"type\":\"string\",\"default\":\"UNKNOWN\"},{\"name\":\"active\",\"type\":\"boolean\",\"default\":false}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avro01> ENCODER =
      new BinaryMessageEncoder<Avro01>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avro01> DECODER =
      new BinaryMessageDecoder<Avro01>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Avro01> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Avro01> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Avro01> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Avro01>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Avro01 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Avro01 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Avro01 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Avro01 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence fullName;
  private java.lang.CharSequence maritalStatus;
  private boolean active;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avro01() {}

  /**
   * All-args constructor.
   * @param fullName The new value for fullName
   * @param maritalStatus The new value for maritalStatus
   * @param active The new value for active
   */
  public Avro01(java.lang.CharSequence fullName, java.lang.CharSequence maritalStatus, java.lang.Boolean active) {
    this.fullName = fullName;
    this.maritalStatus = maritalStatus;
    this.active = active;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return fullName;
    case 1: return maritalStatus;
    case 2: return active;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: fullName = (java.lang.CharSequence)value$; break;
    case 1: maritalStatus = (java.lang.CharSequence)value$; break;
    case 2: active = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'fullName' field.
   * @return The value of the 'fullName' field.
   */
  public java.lang.CharSequence getFullName() {
    return fullName;
  }


  /**
   * Sets the value of the 'fullName' field.
   * @param value the value to set.
   */
  public void setFullName(java.lang.CharSequence value) {
    this.fullName = value;
  }

  /**
   * Gets the value of the 'maritalStatus' field.
   * @return The value of the 'maritalStatus' field.
   */
  public java.lang.CharSequence getMaritalStatus() {
    return maritalStatus;
  }


  /**
   * Sets the value of the 'maritalStatus' field.
   * @param value the value to set.
   */
  public void setMaritalStatus(java.lang.CharSequence value) {
    this.maritalStatus = value;
  }

  /**
   * Gets the value of the 'active' field.
   * @return The value of the 'active' field.
   */
  public boolean getActive() {
    return active;
  }


  /**
   * Sets the value of the 'active' field.
   * @param value the value to set.
   */
  public void setActive(boolean value) {
    this.active = value;
  }

  /**
   * Creates a new Avro01 RecordBuilder.
   * @return A new Avro01 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro01.Builder newBuilder() {
    return new dev.intermediatebox.avro.data.Avro01.Builder();
  }

  /**
   * Creates a new Avro01 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avro01 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro01.Builder newBuilder(dev.intermediatebox.avro.data.Avro01.Builder other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro01.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro01.Builder(other);
    }
  }

  /**
   * Creates a new Avro01 RecordBuilder by copying an existing Avro01 instance.
   * @param other The existing instance to copy.
   * @return A new Avro01 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro01.Builder newBuilder(dev.intermediatebox.avro.data.Avro01 other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro01.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro01.Builder(other);
    }
  }

  /**
   * RecordBuilder for Avro01 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avro01>
    implements org.apache.avro.data.RecordBuilder<Avro01> {

    private java.lang.CharSequence fullName;
    private java.lang.CharSequence maritalStatus;
    private boolean active;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro01.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.fullName)) {
        this.fullName = data().deepCopy(fields()[0].schema(), other.fullName);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.maritalStatus)) {
        this.maritalStatus = data().deepCopy(fields()[1].schema(), other.maritalStatus);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.active)) {
        this.active = data().deepCopy(fields()[2].schema(), other.active);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Avro01 instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro01 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.fullName)) {
        this.fullName = data().deepCopy(fields()[0].schema(), other.fullName);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.maritalStatus)) {
        this.maritalStatus = data().deepCopy(fields()[1].schema(), other.maritalStatus);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.active)) {
        this.active = data().deepCopy(fields()[2].schema(), other.active);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'fullName' field.
      * @return The value.
      */
    public java.lang.CharSequence getFullName() {
      return fullName;
    }


    /**
      * Sets the value of the 'fullName' field.
      * @param value The value of 'fullName'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder setFullName(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.fullName = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'fullName' field has been set.
      * @return True if the 'fullName' field has been set, false otherwise.
      */
    public boolean hasFullName() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'fullName' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder clearFullName() {
      fullName = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'maritalStatus' field.
      * @return The value.
      */
    public java.lang.CharSequence getMaritalStatus() {
      return maritalStatus;
    }


    /**
      * Sets the value of the 'maritalStatus' field.
      * @param value The value of 'maritalStatus'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder setMaritalStatus(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.maritalStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'maritalStatus' field has been set.
      * @return True if the 'maritalStatus' field has been set, false otherwise.
      */
    public boolean hasMaritalStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'maritalStatus' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder clearMaritalStatus() {
      maritalStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'active' field.
      * @return The value.
      */
    public boolean getActive() {
      return active;
    }


    /**
      * Sets the value of the 'active' field.
      * @param value The value of 'active'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder setActive(boolean value) {
      validate(fields()[2], value);
      this.active = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'active' field has been set.
      * @return True if the 'active' field has been set, false otherwise.
      */
    public boolean hasActive() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'active' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro01.Builder clearActive() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avro01 build() {
      try {
        Avro01 record = new Avro01();
        record.fullName = fieldSetFlags()[0] ? this.fullName : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.maritalStatus = fieldSetFlags()[1] ? this.maritalStatus : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.active = fieldSetFlags()[2] ? this.active : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avro01>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avro01>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avro01>
    READER$ = (org.apache.avro.io.DatumReader<Avro01>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.fullName);

    out.writeString(this.maritalStatus);

    out.writeBoolean(this.active);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.fullName = in.readString(this.fullName instanceof Utf8 ? (Utf8)this.fullName : null);

      this.maritalStatus = in.readString(this.maritalStatus instanceof Utf8 ? (Utf8)this.maritalStatus : null);

      this.active = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.fullName = in.readString(this.fullName instanceof Utf8 ? (Utf8)this.fullName : null);
          break;

        case 1:
          this.maritalStatus = in.readString(this.maritalStatus instanceof Utf8 ? (Utf8)this.maritalStatus : null);
          break;

        case 2:
          this.active = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










