/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.intermediatebox.avro.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Sample fixed */
@org.apache.avro.specific.AvroGenerated
public class Avro08 extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7373392723716240808L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Avro08\",\"namespace\":\"dev.intermediatebox.avro.data\",\"doc\":\"Sample fixed\",\"fields\":[{\"name\":\"hash\",\"type\":{\"type\":\"fixed\",\"name\":\"Sha256\",\"size\":32}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Avro08> ENCODER =
      new BinaryMessageEncoder<Avro08>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Avro08> DECODER =
      new BinaryMessageDecoder<Avro08>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Avro08> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Avro08> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Avro08> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Avro08>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Avro08 to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Avro08 from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Avro08 instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Avro08 fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private dev.intermediatebox.avro.data.Sha256 hash;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Avro08() {}

  /**
   * All-args constructor.
   * @param hash The new value for hash
   */
  public Avro08(dev.intermediatebox.avro.data.Sha256 hash) {
    this.hash = hash;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return hash;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: hash = (dev.intermediatebox.avro.data.Sha256)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'hash' field.
   * @return The value of the 'hash' field.
   */
  public dev.intermediatebox.avro.data.Sha256 getHash() {
    return hash;
  }


  /**
   * Sets the value of the 'hash' field.
   * @param value the value to set.
   */
  public void setHash(dev.intermediatebox.avro.data.Sha256 value) {
    this.hash = value;
  }

  /**
   * Creates a new Avro08 RecordBuilder.
   * @return A new Avro08 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro08.Builder newBuilder() {
    return new dev.intermediatebox.avro.data.Avro08.Builder();
  }

  /**
   * Creates a new Avro08 RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Avro08 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro08.Builder newBuilder(dev.intermediatebox.avro.data.Avro08.Builder other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro08.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro08.Builder(other);
    }
  }

  /**
   * Creates a new Avro08 RecordBuilder by copying an existing Avro08 instance.
   * @param other The existing instance to copy.
   * @return A new Avro08 RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Avro08.Builder newBuilder(dev.intermediatebox.avro.data.Avro08 other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Avro08.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Avro08.Builder(other);
    }
  }

  /**
   * RecordBuilder for Avro08 instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Avro08>
    implements org.apache.avro.data.RecordBuilder<Avro08> {

    private dev.intermediatebox.avro.data.Sha256 hash;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro08.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing Avro08 instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Avro08 other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.hash)) {
        this.hash = data().deepCopy(fields()[0].schema(), other.hash);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'hash' field.
      * @return The value.
      */
    public dev.intermediatebox.avro.data.Sha256 getHash() {
      return hash;
    }


    /**
      * Sets the value of the 'hash' field.
      * @param value The value of 'hash'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro08.Builder setHash(dev.intermediatebox.avro.data.Sha256 value) {
      validate(fields()[0], value);
      this.hash = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'hash' field has been set.
      * @return True if the 'hash' field has been set, false otherwise.
      */
    public boolean hasHash() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'hash' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Avro08.Builder clearHash() {
      hash = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Avro08 build() {
      try {
        Avro08 record = new Avro08();
        record.hash = fieldSetFlags()[0] ? this.hash : (dev.intermediatebox.avro.data.Sha256) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Avro08>
    WRITER$ = (org.apache.avro.io.DatumWriter<Avro08>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Avro08>
    READER$ = (org.apache.avro.io.DatumReader<Avro08>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeFixed(this.hash.bytes(), 0, 32);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      if (this.hash == null) {
        this.hash = new dev.intermediatebox.avro.data.Sha256();
      }
      in.readFixed(this.hash.bytes(), 0, 32);

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          if (this.hash == null) {
            this.hash = new dev.intermediatebox.avro.data.Sha256();
          }
          in.readFixed(this.hash.bytes(), 0, 32);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










