/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package dev.intermediatebox.avro.data;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Company extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3939634360301312208L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Company\",\"namespace\":\"dev.intermediatebox.avro.data\",\"fields\":[{\"name\":\"branches\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"Branch\",\"fields\":[{\"name\":\"address\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"branchId\",\"type\":\"long\"},{\"name\":\"city\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"country\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},\"java-class\":\"java.util.List\"}},{\"name\":\"code\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"companyId\",\"type\":\"long\"},{\"name\":\"name\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Company> ENCODER =
      new BinaryMessageEncoder<Company>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Company> DECODER =
      new BinaryMessageDecoder<Company>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Company> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Company> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Company> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Company>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Company to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Company from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Company instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Company fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.util.List<dev.intermediatebox.avro.data.Branch> branches;
  private java.lang.String code;
  private long companyId;
  private java.lang.String name;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Company() {}

  /**
   * All-args constructor.
   * @param branches The new value for branches
   * @param code The new value for code
   * @param companyId The new value for companyId
   * @param name The new value for name
   */
  public Company(java.util.List<dev.intermediatebox.avro.data.Branch> branches, java.lang.String code, java.lang.Long companyId, java.lang.String name) {
    this.branches = branches;
    this.code = code;
    this.companyId = companyId;
    this.name = name;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return branches;
    case 1: return code;
    case 2: return companyId;
    case 3: return name;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: branches = (java.util.List<dev.intermediatebox.avro.data.Branch>)value$; break;
    case 1: code = value$ != null ? value$.toString() : null; break;
    case 2: companyId = (java.lang.Long)value$; break;
    case 3: name = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'branches' field.
   * @return The value of the 'branches' field.
   */
  public java.util.List<dev.intermediatebox.avro.data.Branch> getBranches() {
    return branches;
  }


  /**
   * Sets the value of the 'branches' field.
   * @param value the value to set.
   */
  public void setBranches(java.util.List<dev.intermediatebox.avro.data.Branch> value) {
    this.branches = value;
  }

  /**
   * Gets the value of the 'code' field.
   * @return The value of the 'code' field.
   */
  public java.lang.String getCode() {
    return code;
  }


  /**
   * Sets the value of the 'code' field.
   * @param value the value to set.
   */
  public void setCode(java.lang.String value) {
    this.code = value;
  }

  /**
   * Gets the value of the 'companyId' field.
   * @return The value of the 'companyId' field.
   */
  public long getCompanyId() {
    return companyId;
  }


  /**
   * Sets the value of the 'companyId' field.
   * @param value the value to set.
   */
  public void setCompanyId(long value) {
    this.companyId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.String getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.String value) {
    this.name = value;
  }

  /**
   * Creates a new Company RecordBuilder.
   * @return A new Company RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Company.Builder newBuilder() {
    return new dev.intermediatebox.avro.data.Company.Builder();
  }

  /**
   * Creates a new Company RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Company RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Company.Builder newBuilder(dev.intermediatebox.avro.data.Company.Builder other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Company.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Company.Builder(other);
    }
  }

  /**
   * Creates a new Company RecordBuilder by copying an existing Company instance.
   * @param other The existing instance to copy.
   * @return A new Company RecordBuilder
   */
  public static dev.intermediatebox.avro.data.Company.Builder newBuilder(dev.intermediatebox.avro.data.Company other) {
    if (other == null) {
      return new dev.intermediatebox.avro.data.Company.Builder();
    } else {
      return new dev.intermediatebox.avro.data.Company.Builder(other);
    }
  }

  /**
   * RecordBuilder for Company instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Company>
    implements org.apache.avro.data.RecordBuilder<Company> {

    private java.util.List<dev.intermediatebox.avro.data.Branch> branches;
    private java.lang.String code;
    private long companyId;
    private java.lang.String name;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Company.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.branches)) {
        this.branches = data().deepCopy(fields()[0].schema(), other.branches);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.companyId)) {
        this.companyId = data().deepCopy(fields()[2].schema(), other.companyId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing Company instance
     * @param other The existing instance to copy.
     */
    private Builder(dev.intermediatebox.avro.data.Company other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.branches)) {
        this.branches = data().deepCopy(fields()[0].schema(), other.branches);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.code)) {
        this.code = data().deepCopy(fields()[1].schema(), other.code);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.companyId)) {
        this.companyId = data().deepCopy(fields()[2].schema(), other.companyId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.name)) {
        this.name = data().deepCopy(fields()[3].schema(), other.name);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'branches' field.
      * @return The value.
      */
    public java.util.List<dev.intermediatebox.avro.data.Branch> getBranches() {
      return branches;
    }


    /**
      * Sets the value of the 'branches' field.
      * @param value The value of 'branches'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder setBranches(java.util.List<dev.intermediatebox.avro.data.Branch> value) {
      validate(fields()[0], value);
      this.branches = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'branches' field has been set.
      * @return True if the 'branches' field has been set, false otherwise.
      */
    public boolean hasBranches() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'branches' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder clearBranches() {
      branches = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'code' field.
      * @return The value.
      */
    public java.lang.String getCode() {
      return code;
    }


    /**
      * Sets the value of the 'code' field.
      * @param value The value of 'code'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder setCode(java.lang.String value) {
      validate(fields()[1], value);
      this.code = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'code' field has been set.
      * @return True if the 'code' field has been set, false otherwise.
      */
    public boolean hasCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'code' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder clearCode() {
      code = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyId' field.
      * @return The value.
      */
    public long getCompanyId() {
      return companyId;
    }


    /**
      * Sets the value of the 'companyId' field.
      * @param value The value of 'companyId'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder setCompanyId(long value) {
      validate(fields()[2], value);
      this.companyId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'companyId' field has been set.
      * @return True if the 'companyId' field has been set, false otherwise.
      */
    public boolean hasCompanyId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'companyId' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder clearCompanyId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.String getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder setName(java.lang.String value) {
      validate(fields()[3], value);
      this.name = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public dev.intermediatebox.avro.data.Company.Builder clearName() {
      name = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Company build() {
      try {
        Company record = new Company();
        record.branches = fieldSetFlags()[0] ? this.branches : (java.util.List<dev.intermediatebox.avro.data.Branch>) defaultValue(fields()[0]);
        record.code = fieldSetFlags()[1] ? this.code : (java.lang.String) defaultValue(fields()[1]);
        record.companyId = fieldSetFlags()[2] ? this.companyId : (java.lang.Long) defaultValue(fields()[2]);
        record.name = fieldSetFlags()[3] ? this.name : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Company>
    WRITER$ = (org.apache.avro.io.DatumWriter<Company>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Company>
    READER$ = (org.apache.avro.io.DatumReader<Company>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.branches.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (dev.intermediatebox.avro.data.Branch e0: this.branches) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

    out.writeString(this.code);

    out.writeLong(this.companyId);

    out.writeString(this.name);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<dev.intermediatebox.avro.data.Branch> a0 = this.branches;
      if (a0 == null) {
        a0 = new SpecificData.Array<dev.intermediatebox.avro.data.Branch>((int)size0, SCHEMA$.getField("branches").schema());
        this.branches = a0;
      } else a0.clear();
      SpecificData.Array<dev.intermediatebox.avro.data.Branch> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<dev.intermediatebox.avro.data.Branch>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          dev.intermediatebox.avro.data.Branch e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new dev.intermediatebox.avro.data.Branch();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

      this.code = in.readString();

      this.companyId = in.readLong();

      this.name = in.readString();

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<dev.intermediatebox.avro.data.Branch> a0 = this.branches;
          if (a0 == null) {
            a0 = new SpecificData.Array<dev.intermediatebox.avro.data.Branch>((int)size0, SCHEMA$.getField("branches").schema());
            this.branches = a0;
          } else a0.clear();
          SpecificData.Array<dev.intermediatebox.avro.data.Branch> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<dev.intermediatebox.avro.data.Branch>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              dev.intermediatebox.avro.data.Branch e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new dev.intermediatebox.avro.data.Branch();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        case 1:
          this.code = in.readString();
          break;

        case 2:
          this.companyId = in.readLong();
          break;

        case 3:
          this.name = in.readString();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










